### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by vladignatyev** [st4lk/django-affiliate#1]
Hi there,
I use your package in production and have few minor changes I want to add, in addition I want to cover the package with tests.

Can anyone help me with that? Any chance to get on Skype to do some code-review? It could help a lot. My skype is: vladimir.ignatyev. I'd be happy to meet you.

**Comment by st4lk** [comment]
Hello, Vladimir! Thanks for activity!
I've accepted corresponding pull-request #2 
But, i make some changes after that, please check recent commits (for example, i've added Pillow instead of deprecated PIL to affiliate dependencies, removed dateutil to keep as small dependencies as possible).
Also, i upload package to pypi! Now it is possible to `pip install django-affiliate`.

**Comment by st4lk** [comment]
I think we can close this issue.
Pull request was accepted and new changes where applied.
